name: Deploy to AWS

on:
  repository_dispatch:
    types: [deploy]  # listen for the deploy event type

permissions:
  actions: read   # read access to check ci pipeline

jobs:

  # in real world scenario would most likely just use one cicd yaml file but want to experiment, need this dummy job for the gh actions graph to look nice

  initialize:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Workflow
        run: echo "Workflow Initialized"

  deploy:
    runs-on: ubuntu-latest
    needs: [CI Pipeline]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2
        if: success()
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${EC2_HOST} << 'EOF'

            cd laravel-products-api
            git pull origin main

            composer install --no-dev
            php artisan migrate --force

            sudo supervisorctl restart laravel-products-api


          EOF
