name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'

      - name: Install Composer dependencies
        run: composer install # dont have any yet

      - name: Run tests
        run: php artisan test  # dont have any tests yet
