name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write
  actions: read  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: php artisan test  # dont have any tests yet
      
      - name: Trigger CD Pipeline
        if: success() && github.ref == 'refs/heads/main'  # only trigger if on main branch and CI passes
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'deploy'
            })
