name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'  
  pull_request:
    branches:
      - main
      - develop

permissions:
  actions: read    # Read access to check CI pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.12'

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2
        if: success()
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${EC2_HOST} << 'EOF'
            cd laravel-products-api
            git pull origin main

            composer install --no-dev
            php artisan migrate --force

            sudo supervisorctl restart laravel-products-api
          EOF

